### ISSUE TITLE
Why does it need internet access?

### ISSUE THREAD

**Issue by rugk** [flathub/org.gnome.SimpleScan#32]
Is internet access really needed for a scanner app? I don't quite understand why it would need this.

Removing this could strengthen the sandbox…

https://github.com/flathub/org.gnome.SimpleScan/blob/ee5eb5b936de79d6c9d2f6f4ddea30fa1c29bbea/org.gnome.SimpleScan.json#L13

**Comment by hfiguiere** [comment]
it's not "internet access". It's network access. There are scanner than can be used over the (local) network.

**Comment by rugk** [comment]
Ah well… obviously, I am dumb. GNOME Software just displays it as "Network access: Can access to the internet" with a yellow warning, which is obviously somewhat simplified hmm…

**Comment by rugk** [comment]
Same on https://flathub.org/apps/org.gnome.SimpleScan:
![Bildschirmfoto am 2024-10-16 um 19 16 19](https://github.com/user-attachments/assets/1e086913-8e1f-47da-b46c-ff7e0b28c90a)

**Comment by hfiguiere** [comment]
Gnome software is wrong.

**Comment by A6GibKm** [comment]
However, the message is not entirely wrong. The app could use the internet if it wanted. Unfortunately, there is no fine grained network permission in flatpak.

**Comment by rugk** [comment]
Yeah, let's keep this discussion to the other ticket(s), I've found one and commented there…
